name: Deploy Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DB_URL: ${{ secrets.DB_SECRETS.DB_URL }}
      DB_USER: ${{ secrets.DB_SECRETS.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_SECRETS.DB_PASSWORD }}
      DB_DRIVER: ${{ secrets.DB_SECRETS }}
      DB_DRIVER2: ${{ secrets.DB_DRIVER }}

    steps:
      - name: Print Environment Variables 1
        run: |
          echo "DB_DRIVER: $DB_DRIVER"
      - name: Print Environment Variables 2
      
        run: |
          echo "DB_DRIVER: $DB_DRIVER2"
          
