name: Deploy Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DB_URL: ${{ secrets.DB_SECRETS.DB_URL }}
      DB_USER: ${{ secrets.DB_SECRETS.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_SECRETS.DB_PASSWORD }}
      DB_DRIVER: ${{ secrets.DB_SECRETS.DB_DRIVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Deploy
        run:  sudo mvn clean install

      - name: Complete
        run: sudo java -jar [Location of jar] &
