name: Deploy Spring Boot App

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build and Deploy
      - name: Build with Maven
        run:  mvn clean package

      # Step 4: Upload .jar file to the droplet
      - name: Deploy to DigitalOcean Droplet
        env:
          DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
        run: |
          # Save the SSH key to a temporary file and set permissions
          echo "$DROPLET_SSH_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          
          # Define the .jar file path (adjust based on your Maven project structure)
          JAR_FILE=$(ls target/*.jar)
          
          # Copy the .jar file to the droplet
          scp -i /tmp/deploy_key -o StrictHostKeyChecking=no $JAR_FILE $DROPLET_USER@$DROPLET_IP:/home/test/chefcorner.jar
          
          # SSH into the droplet and restart the application service
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP << 'EOF'
            sudo systemctl restart chefcorner.service
          EOF

      # Step 5: Clean up the SSH key
      - name: Clean up
        run: rm -f /tmp/deploy_key
