name: Deploy Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
            java-version: '21'
            distribution: 'temurin'

      - name: Create .env file
        run: |
          echo DB_DRIVER=${{ secrets.DB_DRIVER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_URL=${{ secrets.DB_URL }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env

      - name: Build and Deploy
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DRIVER: ${{ secrets.DB_DRIVER }}
        run:  export $(grep -v '^#' .env | xargs) && mvn clean package -DDB_URL="$DB_URL" -DDB_USERNAME="$DB_USERNAME" -DDB_PASSWORD="$DB_PASSWORD"
      
#      - name: Complete
#        env:
#          DB_URL: ${{ secrets.DB_URL }}
#          DB_USER: ${{ secrets.DB_USER }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#          DB_DRIVER: com.mysql.cj.jdbc.Driver
#        run: |
#          sudo java -DDB_URL="${{ secrets.DB_URL }}" \
#            -DDB_USER="${{ secrets.DB_USER }}" \
#            -DDB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
#            -DDB_DRIVER="com.mysql.cj.jdbc.Driver" \
#            -jar target/chefcorner.jar &

